<a href="https://colab.research.google.com/github/lismarcarolinacamacho/PYTHON-tkinter/blob/main/prueba_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
array = np.array([[1,2,3,4],[5,6,7,8]], dtype=np.int64)
print(array)

[[1 2 3 4]
 [5 6 7 8]]


**matrices vacias**

In [6]:
espacio1 = np.arange(0,40,5)
print(espacio1)

[ 0  5 10 15 20 25 30 35]


In [11]:
espacio2 = np.arange(0,50,2)
print(espacio2)

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48]


**matriz de identidad**

In [12]:
identidad1 = np.eye(4,4)
print(identidad1)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [13]:
identidad2 = np.identity(4)
print(identidad2)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
