<a href="https://colab.research.google.com/github/lismarcarolinacamacho/PYTHON-tkinter/blob/main/prueba_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
array = np.array([[1,2,3,4],[5,6,7,8]], dtype=np.int64)
print(array)

[[1 2 3 4]
 [5 6 7 8]]


**matrices vacias**

In [ ]:
espacio1 = np.arange(0,40,5)
print(espacio1)

[ 0  5 10 15 20 25 30 35]


In [ ]:
espacio2 = np.arange(0,50,2)
print(espacio2)

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48]


**matriz de identidad**

In [ ]:
identidad1 = np.eye(4,4)
print(identidad1)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
identidad2 = np.identity(4)
print(identidad2)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


**inspeccionar matrices**

In [ ]:
a = np.array([(1,2,3,4,5,6)])
print(a.size) # tamaño del array
print(a.shape)
#shape :rango
 

6
(1, 6)


cambio de tamaño y forma de matrices

In [ ]:
#extraer un solo valor de la matriz - el valor ubicado en la fila 0 de la columna 2

a =np.array([(1,2,3,4),(3,4,5,6)])
print(a[0,2])

3


In [ ]:
#extrraer todos los valores de las filas ubicadas en la columna 3 
a = np.array([(1,2,3,4),(3,4,5,6)])
print(a[0:,3])

[4 6]


**operaciones matematicas**

In [ ]:
#minimo , maximo, suma

a = np.array([1,2,3,4])
print(a.max())
print(a.min())
print(a.sum())

4
1
10


In [ ]:
# raiz cudrada y desviacion estandar

a = np.array([(1,2,3,4),(3,4,5,6)])
print(np.sqrt(a))
print(np.std(a))

[[1.         1.41421356 1.73205081 2.        ]
 [1.73205081 2.         2.23606798 2.44948974]]
1.5


In [ ]:
x = np.array([(1,2,3,4),(3,4,5,6)])
y = np.array([(1,2,3,4),(3,4,5,6)])

print(x+y)
print(x-y)
print(x*y)
print(x/y)

[[ 2  4  6  8]
 [ 6  8 10 12]]
[[0 0 0 0]
 [0 0 0 0]]
[[ 1  4  9 16]
 [ 9 16 25 36]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
